# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'degerlendirme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QLabel
from PyQt5.QtGui import QPixmap


class ClickableImage(QLabel):
    clicked = pyqtSignal()
    
    def __init__(self, image_path, parent=None):
        super(ClickableImage, self).__init__(parent)
        self.setPixmap(image_path)
        
    def mousePressEvent(self, event):
        self.clicked.emit()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(562, 295)
        self.degerlendirButon = QtWidgets.QPushButton(Form)
        self.degerlendirButon.setGeometry(QtCore.QRect(230, 200, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.degerlendirButon.setFont(font)
        self.degerlendirButon.setObjectName("degerlendirButon")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 70, 351, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yildiz1 = ClickableImage(QPixmap("ui/yıldızdolu.png"))
        self.yildiz1.setText("")
        self.yildiz1.setScaledContents(True)
        self.yildiz1.setObjectName("yildiz1")
        self.horizontalLayout_2.addWidget(self.yildiz1)
        self.yildiz2 = ClickableImage(QPixmap("ui/yıldızbos.png"))
        self.yildiz2.setText("")
        self.yildiz2.setScaledContents(True)
        self.yildiz2.setObjectName("yildiz2")
        self.horizontalLayout_2.addWidget(self.yildiz2)
        self.yildiz3 = ClickableImage(QPixmap("ui/yıldızbos.png"))
        self.yildiz3.setText("")
        self.yildiz3.setScaledContents(True)
        self.yildiz3.setObjectName("yildiz3")
        self.horizontalLayout_2.addWidget(self.yildiz3)
        self.yildiz4 = ClickableImage(QPixmap("ui/yıldızbos.png"))
        self.yildiz4.setText("")
        self.yildiz4.setScaledContents(True)
        self.yildiz4.setObjectName("yildiz4")
        self.horizontalLayout_2.addWidget(self.yildiz4)
        self.yildiz5 = ClickableImage(QPixmap("ui/yıldızbos.png"))
        self.yildiz5.setText("")
        self.yildiz5.setScaledContents(True)
        self.yildiz5.setObjectName("yildiz5")
        self.horizontalLayout_2.addWidget(self.yildiz5)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-40, 60, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.degerlendirButon.setText(_translate("Form", "Değerlendir"))
        self.label.setText(_translate("Form", "Tarif"))
